passes R CMD check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -586,6 +586,7 @@ ac_subst_vars='LTLIBOBJS
 LIBOBJS
 CLANG_LIB
 CLANG_INC
+LLVM_CONFIG
 target_alias
 host_alias
 build_alias
@@ -1675,6 +1676,77 @@ if ! test "x$CLANG_DIR" = "x" ; then
      CLANG_INC=$CLANG_DIR/tools/clang/include
   fi
 fi
+
+if test -z "$CLANG_LIB" || test -z "$CLANG_INC" ; then
+ echo "Trying to find include and library directories via llvm-config"
+ if test -z "${LLVM_CONFIG}" ; then
+echo "$PATH"
+   # Extract the first word of "llvm-config", so it can be a program name with args.
+set dummy llvm-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_LLVM_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $LLVM_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LLVM_CONFIG="$LLVM_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in ${PATH}
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_LLVM_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+LLVM_CONFIG=$ac_cv_path_LLVM_CONFIG
+if test -n "$LLVM_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $LLVM_CONFIG" >&5
+$as_echo "$LLVM_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+ elif ! (test -f "$LLVM_CONFIG" && test -x "$LLVM_CONFIG") ; then
+    echo "${LLVM_CONFIG} is not an executable command"
+    exit 1;
+ fi
+
+
+ if test -n "${LLVM_CONFIG}" ; then
+
+    TMP=`${LLVM_CONFIG}  --includedir`
+    if test -d $TMP/clang-c && test -e $TMP/clang-c/Index.h ; then
+       CLANG_INC=$TMP
+       echo "Found clang-c at $TMP/clang-c"
+    else
+       echo "*** Couldn't find clang-c using ${LLVM_CONFIG}"
+    fi
+
+    TMP=`${LLVM_CONFIG}  --libdir`
+    if test -e $TMP/libclang.so || test -e $TMP/libclang.a ; then
+       CLANG_LIB=$TMP
+       echo "Found libclang at $CLANG_LIB"
+    else
+       echo "*** Couldn't find libclang using ${LLVM_CONFIG}"
+    fi
+  fi
+fi
+
 
 if test -z "$CLANG_LIB" || test -z "$CLANG_INC" ; then
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -14,6 +14,37 @@ if ! test "x$CLANG_DIR" = "x" ; then
 fi
 
 if test -z "$CLANG_LIB" || test -z "$CLANG_INC" ; then
+ echo "Trying to find include and library directories via llvm-config"
+ if test -z "${LLVM_CONFIG}" ; then
+   AC_PATH_PROG(LLVM_CONFIG, llvm-config, , ${PATH})
+ elif ! (test -f "$LLVM_CONFIG" && test -x "$LLVM_CONFIG") ; then
+    echo "${LLVM_CONFIG} is not an executable command"
+    exit 1;
+ fi
+
+
+ if test -n "${LLVM_CONFIG}" ; then
+
+    TMP=`${LLVM_CONFIG}  --includedir`
+    if test -d $TMP/clang-c && test -e $TMP/clang-c/Index.h ; then 
+       CLANG_INC=$TMP
+       echo "Found clang-c at $TMP/clang-c"
+    else
+       echo "*** Couldn't find clang-c using ${LLVM_CONFIG}"
+    fi
+
+    TMP=`${LLVM_CONFIG}  --libdir`
+    if test -e $TMP/libclang.so || test -e $TMP/libclang.a ; then 
+       CLANG_LIB=$TMP
+       echo "Found libclang at $CLANG_LIB"
+    else
+       echo "*** Couldn't find libclang using ${LLVM_CONFIG}"
+    fi
+  fi
+fi
+
+
+if test -z "$CLANG_LIB" || test -z "$CLANG_INC" ; then
 
   if test -r $HOME/llvm-devel/tools/clang/include/clang-c ; then
      CLANG_INC=$HOME/llvm-devel/tools/clang/include/
